bboard_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='')),
    path('users/', include('users.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('api/', include('rest_api.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import CategoryDetailView
from .views import SubcategoryDetailView
from .views import index
from .views import additional_page
from .views import by_region
from .views import ad_detail
from .views import ad_create
from .views import ad_delete
from .views import ad_update
from .views import favorite_ad
from .views import favorite_ads_list

app_name = 'main'

urlpatterns = [
    path('<str:slug>/update/', ad_update, name='ad_update'),
    path('<str:slug>/detail/', ad_detail, name='ad_detail'),
    path('<str:slug>/delete/', ad_delete, name='ad_delete'),
    path('create/', ad_create, name='ad_create'),
    path('favorite_ads_list/', favorite_ads_list, name='favorite_ads_list'),
    path('<str:slug>/favorite_ad/', favorite_ad, name='favorite_ad'),
    path('<str:slug>/subcategory/', SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('<str:slug>/category/', CategoryDetailView.as_view(), name='category_detail'),
    path('<str:region>/', by_region, name='by_region'),
    path('<str:page>/', additional_page, name='add_page'),
    path('', index, name='index'),
]

users/urls.py
from django.urls import path

from .views import UserLoginView
from .views import UserLogoutView
from .views import UserProfileEditView
from .views import UserProfileView
from .views import DeleteUserView
from .views import UserPasswordChangeView
from .views import RegisterUserView
from .views import RegisterDoneView
from .views import user_activate
from .views import user_profile_ads


app_name = 'users'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register_user'),
    path('accounts/password/change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/', UserProfileView.as_view(), name='profile'),
    path('accounts/profile/ads/', user_profile_ads, name='user_profile_ads'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='delete_user'),
    path('accounts/profile/edit/', UserProfileEditView.as_view(), name='profile_edit'),
    path('accounts/logout/', UserLogoutView.as_view(), name='user_logout'),
    path('accounts/login/', UserLoginView.as_view(), name='user_login'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse
from django.dispatch import Signal
from django.dispatch import receiver

from .utils import get_timestamp_path
from .utils import send_activation_notification


user_registrated = Signal(providing_args=['instance'])


@receiver(user_registrated)
def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


class CustomUser(AbstractUser):
    """
    Переопределение стандартной модели пользователя
    """
    username = models.CharField(
        max_length=30,
        verbose_name='Ник',
        unique=True,
    )
    is_activated = models.BooleanField(
        default=True,
        db_index=True,
        verbose_name='Прошёл активацию',
    )
    send_comment_notices = models.BooleanField(
        default=True,
        verbose_name='Уведомления о новых комментариях',
    )
    city = models.ForeignKey(
        'UserCity',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        verbose_name='Город',
    )
    phone_number = PhoneNumberField(
        blank=True,
        null=True,
        unique=True,
        verbose_name='Номер телефона',
    )
    address = models.CharField(
        verbose_name='Адрес',
        max_length=70,
        blank=True,
        null=True,
    )
    avatar = models.ImageField(
        blank=True,
        null=True,
        upload_to=get_timestamp_path,
        verbose_name='Аватар',
    )

    def get_absolute_url(self):
        return reverse('users:user_profile_ads', kwargs={'pk': self.pk})

    def delete(self, *args, **kwargs):
        for ad in self.ads.all():
            ad.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class UserCity(models.Model):
    city = models.CharField(
        blank=True,
        null=True,
        max_length=70,
    )

    def __str__(self):
        return self.city

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from phonenumber_field.formfields import PhoneNumberField
from captcha.fields import CaptchaField
from django.utils.safestring import mark_safe
from string import Template
from django.conf import settings

from .models import CustomUser
from .models import user_registrated


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Ваш ник',
        widget=forms.TextInput,
    )
    password = forms.CharField(
        label='Ваш пароль',
        widget=forms.PasswordInput,
    )

    class Meta:
        fields = ['username', 'password']


class UserProfileForm(forms.ModelForm):
    email = forms.EmailField(
        required=True,
        label='Адрес электронной почты',
    )
    phone_number = PhoneNumberField(
        required=True,
        label='Мобильный телефон',
    )

    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'email',
            'city',
            'phone_number',
            'address',
            'avatar',
            'send_comment_notices',
        ]


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(
        required=True,
        label='Адрес электронной почты',
    )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput,
    )
    captcha = CaptchaField()

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {
                'password2': ValidationError(
                    'Пароли не совпадают',
                    code='password_mismatch',
                )
            }
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = CustomUser
        fields = [
            'email',
            'username',
            'first_name',
            'password1',
            'password2',
            'captcha',
        ]

users/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.contrib import messages

from .forms import UserLoginForm
from .forms import UserProfileForm
from .forms import RegisterUserForm
from .models import CustomUser
from .utils import signer
from main.models import Ad


class UserLoginView(LoginView):
    template_name = 'users/registration/login.html'
    authentication_form = UserLoginForm


class UserLogoutView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('main:index')


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'


@login_required
def user_profile_ads(request):
    ads = Ad.objects.filter(author=request.user.pk)
    context = {'ads': ads}
    return render(request, 'users/profile_ads.html', context)


class UserProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = UserProfileForm
    template_name = 'users/profile_edit.html'
    success_url = reverse_lazy('users:profile')
    success_message = 'Профиль отредактирован'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class UserPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:profile')
    success_message = 'Ваш пароль изменён'


class RegisterUserView(CreateView):
    model = CustomUser
    form_class = RegisterUserForm
    template_name = 'users/registration/register_user.html'
    success_url = reverse_lazy('users:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'users/registration/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'users/registration/bad_signature.html')
    user = get_object_or_404(CustomUser, username=username)
    if user.is_activated:
        template = 'users/user_is_activated.html'
    else:
        template = 'users/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = CustomUser
    template_name = 'users/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(
            request,
            messages.SUCCESS,
            'Аккаунт удалён',
        )
        return super().post(request, *args, **kwargs)

users/templates/users/delete_user.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %} Удаление пользователя {% endblock %}</title>
	</head>
	<body>
		{% block content %}
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Удалить">
		</form>
		{% endblock %}
	</body>
</html>

users/templates/users/password_change.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Смена пароля{% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<h2>Смена пароля</h2>
			<form method="post">
				{% csrf_token %}
				{% bootstrap_form form layout='horizontal' %}
				<input type="submit" value="Изменить">
			</form>
		{% endblock %}
	</body>
</html>

users/templates/users/profile.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Профиль{% endblock %}</title>
	</head>
	<body>
		{% block content %}
			{% include 'users/includes/profile_navbar.html' %}
			<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12">
						{% if user.first_name %}
							<h2>Добро пожаловать, {{ user.first_name|capfirst }}</h2>
						{% elif user.username %}
							<h2>Добро пожаловать, {{ user.username }}</h2>
						{% else %}
							<h2>Добро пожаловать</h2>
						{% endif %}
						<h2>Контактные данные</h2>
							{{ user.first_name }}
							{{ user.email }}
							{{ user.city }}
							{{ user.address }}
							{{ user.phone_number }}
							{% if user.avatar %}
								<img src="{{ user.avatar.url }}" alt="avatar">
							{% else %}
								<p>Аватара нет</p>
							{% endif %}
						<h3><a href="{% url 'users:profile_edit' %}">Редактировать профиль</a></h3>
						<h3><a href="{% url 'users:user_logout' %}">Выйти</a></h3>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

users/templates/users/profile_ads.html
{% extends 'layout/basic.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Title</title>
	</head>
	<body>
		{% block content %}
			{% include 'users/includes/profile_navbar.html' %}
		<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list mt-5">
									{% if ads %}
									{% include 'includes/ads.html' %}
									{% else %}
									<h3>Вы ещё не оставили объявления</h3>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

users/templates/users/profile_edit.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Профиль{% endblock %}</title>
	</head>
	<body>
		{% block content %}
			{% include 'users/includes/profile_navbar.html' %}
			<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12">
						{% if user.first_name %}
							<h2>Добро пожаловать, {{ user.first_name|capfirst }}</h2>
						{% elif user.username %}
							<h2>Добро пожаловать, {{ user.username }}</h2>
						{% else %}
							<h2>Добро пожаловать</h2>
						{% endif %}
						<h2>Контактные данные</h2>
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{% bootstrap_messages %}
							{% bootstrap_form form %}
							<input type="submit" value="Сохранить">
						</form>
						<h3><a href="{% url 'users:password_change' %}">Сменить пароль</a></h3>
						<h3><a href="{% url 'users:user_logout' %}">Выйти</a></h3>
						<h3><a href="{% url 'users:delete_user' %}">Удалить профиль</a></h3>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>