bboard_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='')),
    path('users/', include('users.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('api/', include('rest_api.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import CategoryDetailView
from .views import SubcategoryDetailView
from .views import index
from .views import additional_page
from .views import by_region
from .views import ad_detail
from .views import ad_create
from .views import ad_delete
from .views import ad_update
from .views import favorite_ad
from .views import favorite_ads_list

app_name = 'main'

urlpatterns = [
    path('<str:slug>/update/', ad_update, name='ad_update'),
    path('<str:slug>/detail/', ad_detail, name='ad_detail'),
    path('<str:slug>/delete/', ad_delete, name='ad_delete'),
    path('create/', ad_create, name='ad_create'),
    path('favorite_ads_list/', favorite_ads_list, name='favorite_ads_list'),
    path('<str:slug>/favorite_ad/', favorite_ad, name='favorite_ad'),
    path('<str:slug>/subcategory/', SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('<str:slug>/category/', CategoryDetailView.as_view(), name='category_detail'),
    path('<str:region>/', by_region, name='by_region'),
    path('<str:page>/', additional_page, name='add_page'),
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from users.models import CustomUser
from users.utils import get_timestamp_path


class Category(models.Model):
    name = models.CharField(
        max_length=70,
        unique=True,
        db_index=True,
        verbose_name='Название',
    )
    slug = models.SlugField(
        unique=True,
        max_length=80,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:category_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Subcategory(models.Model):
    name = models.CharField(
        max_length=70,
        unique=True,
        db_index=True,
        verbose_name='Название',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='subcategories',
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True,
        max_length=80,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:subcategory_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Ad(models.Model):
    slug = models.SlugField(
        unique=True,
        max_length=80,
        blank=True,
    )
    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.PROTECT,
        related_name='ads',
        verbose_name='Подкатегория',
    )
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='ads',
        verbose_name='Автор',
    )
    title = models.CharField(
        max_length=70,
        verbose_name='Заголовок объявления'
    )
    content = models.TextField(
        verbose_name='Текст объявления',
    )
    image = models.ImageField(
        upload_to=get_timestamp_path,
        blank=True,
        null=True,
        verbose_name='Изображение',
    )
    price = models.FloatField(
        default=0,
        verbose_name='Цена',
    )
    region = models.ForeignKey(
        'Region',
        on_delete=models.PROTECT,
        related_name='ads',
        verbose_name='Регион',
    )
    contact_details = models.TextField(
        verbose_name='Контакты'
    )
    is_active = models.BooleanField(
        default=True,
        db_index=True,
        verbose_name='Показывать объявление',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Опубликовано в'
    )
    favorite = models.ManyToManyField(
        CustomUser,
        related_name='favorites',
        blank=True,
    )

    def get_absolute_url(self):
        return reverse('main:ad_detail', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('main:ad_delete', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('main:ad_update', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        for ai in self.addimgs.all():
            ai.delete()
        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Ad, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Region(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        db_index=True,
        verbose_name='Регион',
    )
    slug = models.SlugField(
        unique=True,
        max_length=80,
        blank=True,
        null=True,
    )

    def get_absolute_url(self):
        return reverse('main:by_region', kwargs={'region': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'


class AdditionalImages(models.Model):
    ad = models.ForeignKey(
        Ad,
        on_delete=models.CASCADE,
        related_name='addimgs',
    )
    image = models.ImageField(
        upload_to=get_timestamp_path,
        blank=True,
        null=True,
        verbose_name='Изображение'
    )

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'


class Comment(models.Model):
    ad = models.ForeignKey(
        Ad,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Объявление',
    )
    author = models.CharField(
        max_length=50,
        verbose_name='Автор',
    )
    is_active = models.BooleanField(
        default=True,
        db_index=True,
        verbose_name='Показывать',
    )
    content = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
        db_index=True,
    )

    def __str__(self):
        return self.ad.title

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['-created_at']

main/forms.py
from django import forms
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .models import Ad
from .models import AdditionalImages
from .models import Comment


class SearchForm(forms.Form):
    keyword = forms.CharField(
        required=False,
        max_length=20,
        label='',
    )


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = '__all__'
        labels = {
            'subcategory': 'Подкатегория',
        }
        widgets = {
            'author': forms.HiddenInput,
            'is_active': forms.HiddenInput,
            'slug': forms.HiddenInput,
            'favorite': forms.HiddenInput,
        }


AddImgsFormset = inlineformset_factory(Ad, AdditionalImages, fields='__all__')


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(
        label='Введите текст с картинки',
        error_messages={'invalid': 'Неверный текст'},
    )

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'ad': forms.HiddenInput}

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.template.loader import get_template
from django.template import TemplateDoesNotExist
from django.http import HttpResponse, Http404
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Category
from .models import Subcategory
from .models import Ad
from .models import Region
from .models import AdditionalImages
from .models import Comment
from .forms import SearchForm
from .forms import AdForm
from .forms import AddImgsFormset
from .forms import GuestCommentForm
from .forms import UserCommentForm
from .filters import AdFilter


def index(request):
    categories = Category.objects.all()
    regions = Region.objects.all()
    ads = Ad.objects.filter(is_active=True)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        ads = ads.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(ads, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {
        'categories': categories,
        'ads': page.object_list,
        'page': page,
        'regions': regions,
        'form': form,
    }
    return render(request, 'main/index.html', context)


def by_region(request, region):
    categories = Category.objects.all()
    regions = Region.objects.all()
    if region == 'kazahstan':
        ads = Ad.objects.filter(is_active=True)
    else:
        ads = Ad.objects.filter(region__slug=region, is_active=True)
    context = {
        'ads': ads,
        'regions': regions,
        'categories': categories,
    }
    return render(request, 'main/by_region.html', context)


class CategoryDetailView(ListView):
    template_name = 'main/category_detail.html'
    context_object_name = 'subcategories'
    paginate_by = 2

    def get_queryset(self):
        return Subcategory.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['current_category'] = Category.objects.get(slug=self.kwargs['slug'])
        context['ads'] = Ad.objects.filter(
            subcategory__category__slug=self.kwargs['slug'],
            is_active=True,
        )
        context['regions'] = Region.objects.all()
        return context


class SubcategoryDetailView(ListView):
    template_name = 'main/subcategory_detail.html'

    def get_queryset(self):
        return Subcategory.objects.filter(slug=self.kwargs['slug'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_category'] = Category.objects.get(subcategories__slug=self.kwargs['slug'])
        context['current_subcategory'] = Subcategory.objects.get(slug=self.kwargs['slug'])
        ads = Ad.objects.filter(subcategory__slug=self.kwargs['slug'], is_active=True)
        context['ads'] = ads
        context['filter'] = AdFilter(self.request.GET, queryset=ads)
        return context


def ad_detail(request, slug):
    ad = get_object_or_404(Ad, slug=slug)
    addimgs = AdditionalImages.objects.filter(ad__slug=slug)
    current_category = Category.objects.get(subcategories__ads__slug=slug)
    current_subcategory = Subcategory.objects.get(ads__slug=slug)
    similar_ads = Ad.objects.filter(subcategory=current_subcategory).exclude(slug=slug)
    is_favorite = False
    if ad.favorite.filter(id=request.user.id).exists():
        is_favorite = True

    comments = Comment.objects.filter(ad__slug=slug, is_active=True)
    initial = {'ad': ad}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save(commit=True)
        else:
            form = c_form
    context = {
        'ad': ad,
        'addimgs': addimgs,
        'current_category': current_category,
        'current_subcategory': current_subcategory,
        'similar_ads': similar_ads,
        'comments': comments,
        'is_favorite': is_favorite,
        'form': form,
    }
    return render(request, 'main/ad_detail.html', context)


def additional_page(request, page):
    try:
        template = get_template(f"main/{page}.html")
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


@login_required
def ad_create(request):
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save()
            formset = AddImgsFormset(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                return redirect('main:index')
    else:
        form = AdForm(initial={'author': request.user.id})
        formset = AddImgsFormset()
        context = {'form': form, 'formset': formset}
        return render(request, 'main/ad_create.html', context)


@login_required
def ad_delete(request, slug):
    ad = get_object_or_404(Ad, slug=slug)
    if request.method == 'POST':
        if ad.author == request.user:
            ad.delete()
        return redirect('main:index')
    else:
        return render(request, 'main/ad_delete.html', {'ad': ad})


@login_required
def favorite_ad(request, slug):
    ad = get_object_or_404(Ad, slug=slug)
    if ad.favorite.filter(id=request.user.id).exists():
        ad.favorite.remove(request.user)
    else:
        ad.favorite.add(request.user)
    return redirect(ad.get_absolute_url())


@login_required
def favorite_ads_list(request):
    favorite_ads = Ad.objects.filter(favorite=request.user.pk)
    context = {'favorite_ads': favorite_ads}
    return render(request, 'main/favorite_ads.html', context)


def ad_update(request, slug):
    ad = get_object_or_404(Ad, slug=slug)
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            ad = form.save()
            formset = AddImgsFormset(request.POST, request.FILES, instance=ad)
            if formset.is_valid():
                formset.save()
                return redirect('main:index')
    else:
        form = AdForm(instance=ad)
        formset = AddImgsFormset(instance=ad)
        context = {'form': form, 'formset': formset}
        return render(request, 'main/ad_create.html', context)

main/templates/main/about.html
{% extends 'layout/basic.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %} О нас {% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<h2>В разработке</h2>
		{% endblock %}
	</body>
</html>

main/templates/main/ad_create.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Создание объявления{% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12">
					<h2>Создание объявления</h2>
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							{% bootstrap_form form layout='horizontal' %}
							{% bootstrap_formset formset layout='horizontal' %}
							<input type="submit" value="Опубликовать">
						</form>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/ad_delete.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Удаление объявления{% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12">
						<h2>Удаление объявления</h2>
						<form method="post">
							{% csrf_token %}
							<input type="submit" value="Удалить">
							<a href="{% url 'main:index' %}">Отмена</a>
						</form>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/ad_detail.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Объявление - {{ ad.title }}{% endblock %}</title>
</head>
<body>
{% block content %}
    <div class="container detail-all">
        <div class="row no-gutters">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="{% url 'main:index' %}">Объявление ></a></li>
                    <li>
                        <a href="{% url 'main:category_detail' slug=current_subcategory.category.slug %}">{{ current_category }}
                            ></a></li>
                    <li>
                        <a href="{% url 'main:subcategory_detail' slug=ad.subcategory.slug %}">{{ current_subcategory }}</a>
                    </li>
                </ul>
            </div>
            <div class="details col-md-8">
                <ul class="main-content-details d-flex flex-column">
                    <li>
                        <div class="main-content-title">
                            <h2>{{ ad.title }}</h2>
                        </div>
                    </li>
                    <li>
                        {% if is_favorite %}
                        <a href="{% url 'main:favorite_ad' slug=ad.slug %}" title="Избранное">
                            <i class="fas fa-star"></i>
                        </a>
                        {% else %}
                        <a href="{% url 'main:favorite_ad' slug=ad.slug %}" title="Избранное">
                            <i class="far fa-star"></i>
                        </a>
                        {% endif %}
                    </li>
                    <li>
                        {% if ad.image %}
                            <img src="{{ ad.image.url }}" alt="img" class="my-img">
                        {% else %}
                            <img src="{% static 'main/images/foto_not_found.png' %}"
                                 alt="img" class="my-img">
                        {% endif %}
                    </li>
                    <li>
                        <div class="main-content-text">
                            <p>{{ ad.content }}</p>
                            <p>
                                {% if ad.author == user %}
                                    <a href="{{ ad.get_edit_url }}">Редактировать</a>
                                    <a href="{{ ad.get_delete_url }}">Удалить</a>
                                {% endif %}
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="contacts cold-md-4">
                <div class="detail-price">{{ ad.price }}тг.</div>
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-number">{{ ad.author.phone_number }}</h5>
                        <div class="card-text">
                            <p>Продавец: {{ ad.author.username }}</p>
                            <p>Адрес: <strong>{{ ad.author.address }}</strong></p>
                            <p>{{ ad.contact_details }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 new-comment">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form layout='horizontal' %}
                    <input type="submit" value="Отправить">
                </form>
            </div>
            <div class="comments col-md-12 mt-5">
                <h3>Все комментарии</h3>
                {% for comment in comments %}
                    <div class="comment my-2 p-2">
                        <h5>{{ comment.autho }}</h5>
                        <p>{{ comment.content }}</p>
                        <p class="text-right font-italic">{{ comment.created_at }}</p>
                        <hr class="divider">
                    </div>
                {% endfor %}
            </div>
            <div class="product-list col-md-12 mt-5">
                <h3>Похожие объявления</h3>
                <ul>
                    {% for sa in similar_ads %}
                        <li>
                            <div class="img-holder">
                                {% if sa.image %}
                                    <img src="{% thumbnail sa.image 'default' %}" alt="img" class="my-img">
                                {% else %}
                                    <img src="{% static 'main/images/foto_not_found.png' %}" width="103" height="103"
                                         alt="img" class="my-img">
                                {% endif %}
                            </div>
                            <div class="content">
                                <div class="top-info">
                                    <div class="info-content">
                                        <div class="title-content"><a
                                                href="{{ sa.get_absolute_url }}">{{ sa.title }}</a>
                                        </div>
                                        <div class="description">{{ sa.content|truncatechars:15 }}</div>
                                        <p>{{ sa.region }}</p>
                                    </div>
                                    <span class="price">{{ sa.price }}тг.</span>
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="bottom-info">{{ sa.created_at }}</div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

main/templates/main/by_region.html
{% extends 'layout/basic.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
		{% block content %}
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="nav-block">
							{% include 'includes/regions.html' %}
							<ul class="nav-list">
								{% include 'includes/categories.html' %}
							</ul>
						</div>
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list">
									{% include 'includes/ads.html' %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/category_detail.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}  {% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="nav-block">
							{% include 'includes/regions.html' %}
							<div class="breadcrumb-holder">
								<ul class="breadcrumb">
									<li><a href="{% url 'main:index' %}">Объявления</a></li>
									<li>->{{ current_category }}</li>
                                    {{ current_region }}
								</ul>
							</div>
							<ul class="nav-list">
								{% include 'includes/subcategories.html' %}
							</ul>
						</div>
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list">
									{% include 'includes/ads.html' %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/favorite_ads.html
{% extends 'layout/basic.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %} Избранное {% endblock %}</title>
	</head>
	<body>
		{% block content %}
			{% include 'users/includes/profile_navbar.html' %}
		<div class="container profile-container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list mt-5">
                                    {% for fav in favorite_ads %}
                                        {{ fav.title }}
                                    {% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/index.html
{% extends 'layout/basic.html' %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Главная{% endblock %}</title>
	</head>
	<body>
		{% block search %}
			{% include 'includes/search.html' %}
		{% endblock %}
		{% block content %}
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="nav-block">
							{% include 'includes/regions.html' %}
							<ul class="nav-list">
								{% include 'includes/categories.html' %}
							</ul>
						</div>
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list">
									{% include 'includes/ads.html' %}
								</ul>
							</div>
						</div>
						{% block pagination %}
							{% include 'includes/pagination.html' %}
						{% endblock %}
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

main/templates/main/subcategory_detail.html
{% extends 'layout/basic.html' %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %} {{ current_subcategory }} {% endblock %}</title>
	</head>
	<body>
		{% block content %}
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-12 main">
						<div class="nav-block">
							{% include 'includes/regions.html' %}
							<div class="breadcrumb-holder">
								<ul class="breadcrumb">
									<li><a href="{% url 'main:index' %}">Объявления</a></li>
									<li>-> <a
											href="{% url 'main:category_detail' slug=current_subcategory.category.slug %}">{{ current_category }}</a>
									</li>
									<li>-> {{ current_subcategory }}</li>
								</ul>
							</div>
							<ul class="nav-list">
								{% include 'includes/subcategories.html' %}
							</ul>
                            <form method="get">
                                {{ filter.form }}
                                <input type="submit" value="Поиск">
                            </form>
						</div>
						<div class="main-wrap">
							<div class="main-content">
								<ul class="product-list">
                                    {% include 'includes/ads_filtered.html' %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>