bboard_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='')),
    path('users/', include('users.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path('api/', include('rest_api.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import CategoryDetailView
from .views import SubcategoryDetailView
from .views import index
from .views import additional_page
from .views import by_region
from .views import ad_detail
from .views import ad_create
from .views import ad_delete
from .views import ad_update
from .views import favorite_ad
from .views import favorite_ads_list

app_name = 'main'

urlpatterns = [
    path('<str:slug>/update/', ad_update, name='ad_update'),
    path('<str:slug>/detail/', ad_detail, name='ad_detail'),
    path('<str:slug>/delete/', ad_delete, name='ad_delete'),
    path('create/', ad_create, name='ad_create'),
    path('favorite_ads_list/', favorite_ads_list, name='favorite_ads_list'),
    path('<str:slug>/favorite_ad/', favorite_ad, name='favorite_ad'),
    path('<str:slug>/subcategory/', SubcategoryDetailView.as_view(), name='subcategory_detail'),
    path('<str:slug>/category/', CategoryDetailView.as_view(), name='category_detail'),
    path('<str:region>/', by_region, name='by_region'),
    path('<str:page>/', additional_page, name='add_page'),
    path('', index, name='index'),
]

users/urls.py
from django.urls import path

from .views import UserLoginView
from .views import UserLogoutView
from .views import UserProfileEditView
from .views import UserProfileView
from .views import DeleteUserView
from .views import UserPasswordChangeView
from .views import RegisterUserView
from .views import RegisterDoneView
from .views import user_activate
from .views import user_profile_ads


app_name = 'users'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register_user'),
    path('accounts/password/change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/', UserProfileView.as_view(), name='profile'),
    path('accounts/profile/ads/', user_profile_ads, name='user_profile_ads'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='delete_user'),
    path('accounts/profile/edit/', UserProfileEditView.as_view(), name='profile_edit'),
    path('accounts/logout/', UserLogoutView.as_view(), name='user_logout'),
    path('accounts/login/', UserLoginView.as_view(), name='user_login'),
]

templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>{% block title %}Объявления{% endblock %}</title>
		{% bootstrap_css %}
		<link rel="stylesheet" href="{% static 'main/styles-index.css' %}">
		<link rel="stylesheet" href="{% static 'font-awesome/css/all.css' %}">
		<link rel="stylesheet" href="{% static 'users/styles-log-in.css' %}">
		<link rel="stylesheet" href="{% static 'users/profile.css' %}">
		{% bootstrap_javascript jquery='slim' %}
	</head>

	<body>
		<div class="container">
			<header>
				<div class="menu-row no-gutters">
					<div class="col-12-md">
						<nav>
							<ul class="topmenu">
								<li>
									<a href="{% url 'main:index' %}"><img src="{% static 'main/images/Logo.png' %}"
									                                      alt="Logo"
									                                      width="120"></a>
								</li>
								<li>
									{% block search %}
									{% endblock %}
								</li>
								<li>
									<a href="{% url 'main:favorite_ads_list' %}" title="Избранное"><i class="far fa-star"></i></a>
								</li>
								<li>
									{% if not user.is_authenticated %}
										<a href="{% url 'users:user_login' %}" title="Личный кабинет"><i
												class="far fa-user"></i></a>
									{% else %}
										<a href="{% url 'users:profile' %}" title="Личный кабинет"><i
												class="far fa-user"></i></a>
									{% endif %}
								</li>
								<li>
									<h5><a href="{% if not user.is_authenticated %}{% url 'users:user_login' %}{% else %}{% url 'main:ad_create' %}{% endif %}">
										Подать объявление
									</a>
									</h5>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</header>
		</div>

		{% block content %}
			<h2>Объявлений нет</h2>
			{% block pagination %}
			{% endblock %}
		{% endblock %}
	</body>
</html>